import type { Package } from "../types";
import { IMG } from "./images";

const iso = (m: number, d: number, y = 2026) =>
  new Date(Date.UTC(y, m - 1, d)).toISOString();

export const packages: Package[] = [
  {
    id: "p1",
    slug: "aegean-solitude",
    title: "Aegean Solitude",
    subtitle: "Seven quiet days on Naxos",
    destinationSlug: "naxos",
    destinationName: "Naxos, Greece",
    categorySlug: "women",
    ageGroups: ["young-adults", "professionals"],
    travelType: "wellness",
    difficulty: "easy",
    durationDays: 7,
    durationNights: 6,
    priceFrom: 3200,
    currency: "USD",
    rating: 4.9,
    reviewCount: 128,
    coverImage: IMG.naxos,
    gallery: [IMG.naxos, IMG.chefchaouen, IMG.safetyPassport],
    overview:
      "A restorative week on Naxos, staying in a women-owned villa above the sea. Slow mornings, guided coastal walks, and evenings spent with a small group of solo women travelers.",
    highlights: [
      "Women-owned villa, verified safe",
      "Private female concierge on call",
      "Sunset sailing on a traditional caïque",
      "Cooking class with a local grandmother",
    ],
    itinerary: [
      { day: 1, title: "Arrival & welcome dinner", summary: "Airport transfer, villa check-in, dinner on the terrace." },
      { day: 2, title: "Coastal walk", summary: "A slow six-kilometre walk along the western coast with a local guide." },
      { day: 3, title: "Marble villages", summary: "Day trip inland to the marble villages of the Tragea." },
      { day: 4, title: "Sailing day", summary: "Full day on a traditional caïque with lunch on board." },
      { day: 5, title: "Rest & spa", summary: "Free morning; afternoon at a nearby olive-oil spa." },
      { day: 6, title: "Cooking & farewell", summary: "Cooking class and farewell dinner under the vines." },
      { day: 7, title: "Departure", summary: "Private transfer to Naxos port or airport." },
    ],
    included: [
      "6 nights in a women-owned villa",
      "All breakfasts, 3 lunches, 4 dinners",
      "Airport transfers",
      "All guided activities",
      "24/7 female concierge",
    ],
    excluded: ["International flights", "Travel insurance", "Personal shopping"],
    hotel: "Villa Aegea (women-owned boutique)",
    meals: "Daily breakfast, selected lunches and dinners",
    transport: "Private minivan for group activities",
    pickup: "Naxos Airport (JNX) or port",
    drop: "Naxos Airport (JNX) or port",
    cancellationPolicy:
      "Free cancellation up to 45 days before departure. 50% refund up to 21 days. No refund thereafter.",
    refundPolicy:
      "Refunds processed within 7 business days to the original payment method.",
    faqs: [
      { q: "Is it safe for solo women?", a: "Yes — every partner passes our 42-point safety protocol and the villa is women-owned." },
      { q: "What's the group size?", a: "Maximum 8 women." },
    ],
    availableDates: [
      { id: "d1", startDate: iso(5, 12), endDate: iso(5, 18), totalSeats: 8, bookedSeats: 5 },
      { id: "d2", startDate: iso(6, 9), endDate: iso(6, 15), totalSeats: 8, bookedSeats: 3 },
      { id: "d3", startDate: iso(9, 15), endDate: iso(9, 21), totalSeats: 8, bookedSeats: 1 },
    ],
    featured: true,
    isWomenSpecial: true,
  },
  {
    id: "p2",
    slug: "blue-city-wander",
    title: "Blue City Wander",
    subtitle: "Six days in Chefchaouen",
    destinationSlug: "chefchaouen",
    destinationName: "Chefchaouen, Morocco",
    categorySlug: "women",
    ageGroups: ["young-adults", "professionals"],
    travelType: "cultural",
    difficulty: "easy",
    durationDays: 6,
    durationNights: 5,
    priceFrom: 2450,
    currency: "USD",
    rating: 4.8,
    reviewCount: 92,
    coverImage: IMG.chefchaouen,
    gallery: [IMG.chefchaouen, IMG.naxos],
    overview:
      "Six days in the blue medina of Chefchaouen, staying in a restored riad in the old town. Small group, women-led guides, and long evenings on the rooftop.",
    highlights: [
      "Riad in the old medina, women-owned",
      "Female local guide throughout",
      "Cooking class with a Chaoui family",
      "Day hike into the Rif mountains",
    ],
    itinerary: [
      { day: 1, title: "Arrival in Tangier, transfer to Chefchaouen", summary: "Private transfer, welcome dinner at the riad." },
      { day: 2, title: "Medina walk", summary: "Guided morning walk through the blue quarter." },
      { day: 3, title: "Rif day hike", summary: "Half-day walk to the Spanish mosque and back." },
      { day: 4, title: "Cooking day", summary: "Cooking class with a local family, followed by an unhurried lunch." },
      { day: 5, title: "Rest & rooftop", summary: "Free day; evening rooftop dinner." },
      { day: 6, title: "Departure", summary: "Private transfer back to Tangier." },
    ],
    included: ["5 nights riad", "All breakfasts and 3 dinners", "Airport transfers", "All guided activities"],
    excluded: ["International flights", "Travel insurance"],
    hotel: "Dar Sabaa (women-owned riad)",
    meals: "Daily breakfast + selected dinners",
    transport: "Private car for transfers",
    pickup: "Tangier Airport (TNG)",
    drop: "Tangier Airport (TNG)",
    cancellationPolicy: "Free cancellation up to 30 days before departure.",
    refundPolicy: "Refunds within 7 business days.",
    faqs: [
      { q: "Do I need to cover my hair?", a: "No — Chefchaouen is relaxed. Modest clothing is appreciated in the medina." },
    ],
    availableDates: [
      { id: "d1", startDate: iso(4, 4), endDate: iso(4, 9), totalSeats: 8, bookedSeats: 6 },
      { id: "d2", startDate: iso(10, 12), endDate: iso(10, 17), totalSeats: 8, bookedSeats: 2 },
    ],
    featured: true,
    isWomenSpecial: true,
  },
  {
    id: "p3",
    slug: "silent-ritual-kyoto",
    title: "The Silent Ritual",
    subtitle: "Nine days in Kyoto & Nara",
    destinationSlug: "kyoto",
    destinationName: "Kyoto, Japan",
    categorySlug: "women",
    ageGroups: ["young-adults", "professionals", "seniors"],
    travelType: "cultural",
    difficulty: "easy",
    durationDays: 9,
    durationNights: 8,
    priceFrom: 4850,
    currency: "USD",
    rating: 4.95,
    reviewCount: 214,
    coverImage: IMG.kyoto,
    gallery: [IMG.kyoto, IMG.safetyPassport],
    overview:
      "Nine days of temples, tea, and quiet. Kyoto as it should be experienced — early mornings, small groups, and access that only a local can arrange.",
    highlights: [
      "Dawn temple visits before the crowds",
      "Private tea ceremony with a Kyoto master",
      "Nara day trip",
      "Ryokan night with kaiseki dinner",
    ],
    itinerary: [
      { day: 1, title: "Arrival Osaka, transfer to Kyoto", summary: "Private transfer, evening walk in Gion." },
      { day: 2, title: "Eastern temples", summary: "Kiyomizu-dera at dawn, then Ninenzaka and Sannenzaka." },
      { day: 3, title: "Northern temples", summary: "Kinkaku-ji and the Zen gardens of Ryoan-ji." },
      { day: 4, title: "Tea ceremony", summary: "Private tea ceremony followed by lunch in an old townhouse." },
      { day: 5, title: "Arashiyama", summary: "Bamboo grove at dawn, then boat trip on the Hozu river." },
      { day: 6, title: "Nara day trip", summary: "Todai-ji, Kasuga shrine, and the deer of Nara park." },
      { day: 7, title: "Ryokan night", summary: "Transfer to a mountain ryokan, onsen bath and kaiseki dinner." },
      { day: 8, title: "Southern Fushimi", summary: "Sunrise at Fushimi Inari, farewell dinner in central Kyoto." },
      { day: 9, title: "Departure", summary: "Transfer to Osaka Airport." },
    ],
    included: ["8 nights (7 boutique hotel, 1 ryokan)", "All breakfasts, 4 dinners", "All transfers", "All guided experiences"],
    excluded: ["International flights", "Travel insurance", "Rail pass extension"],
    hotel: "Boutique machiya + one night ryokan",
    meals: "Daily breakfast, selected dinners including kaiseki",
    transport: "Private car for transfers, local trains during days",
    pickup: "Osaka Kansai Airport (KIX)",
    drop: "Osaka Kansai Airport (KIX)",
    cancellationPolicy: "Free cancellation up to 60 days before departure.",
    refundPolicy: "Refunds within 10 business days.",
    faqs: [{ q: "Is Japanese language required?", a: "No — our guide accompanies the group throughout." }],
    availableDates: [
      { id: "d1", startDate: iso(4, 5), endDate: iso(4, 13), totalSeats: 10, bookedSeats: 8 },
      { id: "d2", startDate: iso(11, 3), endDate: iso(11, 11), totalSeats: 10, bookedSeats: 4 },
    ],
    featured: true,
    isWomenSpecial: true,
  },
  {
    id: "p4",
    slug: "tea-country-sanctuary",
    title: "Tea Country Sanctuary",
    subtitle: "Eight days in Sri Lanka's highlands",
    destinationSlug: "sri-lanka-highlands",
    destinationName: "Sri Lankan Highlands",
    categorySlug: "wellness",
    ageGroups: ["young-adults", "professionals", "seniors"],
    travelType: "wellness",
    difficulty: "easy",
    durationDays: 8,
    durationNights: 7,
    priceFrom: 3200,
    currency: "USD",
    rating: 4.85,
    reviewCount: 76,
    coverImage: IMG.srilanka,
    gallery: [IMG.srilanka, IMG.bali],
    overview:
      "A contemplative journey through the misty highlands of Sri Lanka. Private bungalow stays, train transfers through ancient forests, and guided cultural meditation.",
    highlights: [
      "Colonial bungalow stays",
      "Train through the highlands",
      "Tea plantation walks",
      "Ayurvedic wellness sessions",
    ],
    itinerary: [
      { day: 1, title: "Arrival Colombo", summary: "Rest at a boutique hotel by the sea." },
      { day: 2, title: "Transfer to Kandy", summary: "Temple of the Tooth and evening cultural show." },
      { day: 3, title: "Kandy to Nuwara Eliya", summary: "Scenic train journey through tea country." },
      { day: 4, title: "Plantation walk", summary: "Guided walk on the tea estates." },
      { day: 5, title: "Ella", summary: "Nine Arch Bridge and Little Adam's Peak at dawn." },
      { day: 6, title: "Ayurveda day", summary: "Full day at an Ayurvedic retreat." },
      { day: 7, title: "Return to coast", summary: "Transfer to a coastal boutique hotel." },
      { day: 8, title: "Departure", summary: "Transfer to Colombo airport." },
    ],
    included: ["7 nights across three properties", "All breakfasts, 5 dinners", "All transfers", "Train tickets"],
    excluded: ["International flights", "Travel insurance"],
    hotel: "Colonial bungalow + Ayurvedic retreat",
    meals: "Daily breakfast + selected dinners",
    transport: "Private car + heritage train",
    pickup: "Colombo Airport (CMB)",
    drop: "Colombo Airport (CMB)",
    cancellationPolicy: "Free cancellation up to 45 days before departure.",
    refundPolicy: "Refunds within 7 business days.",
    faqs: [{ q: "Suitable for seniors?", a: "Yes — the pace is deliberately slow." }],
    availableDates: [
      { id: "d1", startDate: iso(2, 8), endDate: iso(2, 15), totalSeats: 12, bookedSeats: 9 },
      { id: "d2", startDate: iso(10, 5), endDate: iso(10, 12), totalSeats: 12, bookedSeats: 3 },
    ],
    featured: true,
    isWomenSpecial: false,
  },
  {
    id: "p5",
    slug: "himalayan-monastery-trek",
    title: "Himalayan Monastery Trek",
    subtitle: "Ten days at altitude",
    destinationSlug: "himalayas",
    destinationName: "Indian Himalayas",
    categorySlug: "adventure",
    ageGroups: ["young-adults", "professionals"],
    travelType: "adventure",
    difficulty: "challenging",
    durationDays: 10,
    durationNights: 9,
    priceFrom: 3900,
    currency: "USD",
    rating: 4.9,
    reviewCount: 58,
    coverImage: IMG.himalayas,
    gallery: [IMG.himalayas, IMG.safetyPassport],
    overview:
      "A ten-day trek visiting three high-altitude monasteries. Moderate to challenging terrain, all technical support provided.",
    highlights: [
      "Three monastery stays",
      "Certified female trek leader",
      "Full altitude acclimatisation",
      "Emergency evacuation cover",
    ],
    itinerary: [
      { day: 1, title: "Arrival Leh", summary: "Rest day for acclimatisation." },
      { day: 2, title: "Local acclimatisation", summary: "Short walks around Leh." },
      { day: 3, title: "Drive to trailhead", summary: "Transfer and light walk." },
      { day: 4, title: "Trek day 1", summary: "Walk to first monastery." },
      { day: 5, title: "Rest & monastery day", summary: "Day at first monastery." },
      { day: 6, title: "Trek day 2", summary: "Walk to second monastery." },
      { day: 7, title: "Trek day 3", summary: "Walk to third monastery." },
      { day: 8, title: "Return leg", summary: "Descent begins." },
      { day: 9, title: "Return to Leh", summary: "Rest and celebration dinner." },
      { day: 10, title: "Departure", summary: "Transfer to Leh Airport." },
    ],
    included: ["9 nights (guesthouse + monastery)", "All meals", "All permits", "Certified guide", "Emergency evacuation"],
    excluded: ["Domestic flights to Leh", "Personal trek gear"],
    hotel: "Guesthouses + monastery stays",
    meals: "All meals on trek",
    transport: "Private jeep + walking",
    pickup: "Leh Airport (IXL)",
    drop: "Leh Airport (IXL)",
    cancellationPolicy: "Free cancellation up to 60 days before departure.",
    refundPolicy: "Refunds within 10 business days.",
    faqs: [{ q: "Fitness required?", a: "Moderate to good; ability to walk 5–6 hours a day at altitude." }],
    availableDates: [
      { id: "d1", startDate: iso(7, 4), endDate: iso(7, 13), totalSeats: 10, bookedSeats: 6 },
      { id: "d2", startDate: iso(8, 15), endDate: iso(8, 24), totalSeats: 10, bookedSeats: 3 },
    ],
    featured: false,
    isWomenSpecial: false,
  },
  {
    id: "p6",
    slug: "bali-family-week",
    title: "Bali Family Week",
    subtitle: "Seven days for every generation",
    destinationSlug: "bali",
    destinationName: "Bali, Indonesia",
    categorySlug: "family",
    ageGroups: ["kids", "families", "seniors"],
    travelType: "leisure",
    difficulty: "easy",
    durationDays: 7,
    durationNights: 6,
    priceFrom: 4200,
    currency: "USD",
    rating: 4.8,
    reviewCount: 143,
    coverImage: IMG.bali,
    gallery: [IMG.bali, IMG.srilanka],
    overview:
      "A week designed for families of every age — Ubud's rice terraces, temple mornings, a beach base, and kid-tested activities.",
    highlights: [
      "Family villa with pool",
      "Kids club with certified staff",
      "Traditional cooking class",
      "Snorkelling day",
    ],
    itinerary: [
      { day: 1, title: "Arrival Denpasar", summary: "Transfer to Ubud family villa." },
      { day: 2, title: "Rice terraces", summary: "Morning walk + waterfall swim." },
      { day: 3, title: "Cooking day", summary: "Family cooking class." },
      { day: 4, title: "Transfer to coast", summary: "Move to a beach villa." },
      { day: 5, title: "Snorkelling", summary: "Day boat to reef." },
      { day: 6, title: "Beach day", summary: "Free day at the villa." },
      { day: 7, title: "Departure", summary: "Transfer to Denpasar Airport." },
    ],
    included: ["6 nights villa stays", "All breakfasts, 3 dinners", "All transfers", "Kids club"],
    excluded: ["International flights"],
    hotel: "Family villas (Ubud + coast)",
    meals: "Breakfast daily",
    transport: "Private van for transfers",
    pickup: "Denpasar Airport (DPS)",
    drop: "Denpasar Airport (DPS)",
    cancellationPolicy: "Free cancellation up to 30 days before departure.",
    refundPolicy: "Refunds within 7 business days.",
    faqs: [{ q: "Youngest age?", a: "We host children from 3 years up." }],
    availableDates: [
      { id: "d1", startDate: iso(6, 20), endDate: iso(6, 26), totalSeats: 16, bookedSeats: 11 },
      { id: "d2", startDate: iso(12, 22), endDate: iso(12, 28), totalSeats: 16, bookedSeats: 4 },
    ],
    featured: true,
    isWomenSpecial: false,
  },
  {
    id: "p7",
    slug: "iceland-solitude",
    title: "Iceland Solitude",
    subtitle: "Six days on the south coast",
    destinationSlug: "iceland",
    destinationName: "Iceland",
    categorySlug: "international",
    ageGroups: ["young-adults", "professionals"],
    travelType: "adventure",
    difficulty: "moderate",
    durationDays: 6,
    durationNights: 5,
    priceFrom: 3600,
    currency: "USD",
    rating: 4.85,
    reviewCount: 71,
    coverImage: IMG.iceland,
    gallery: [IMG.iceland],
    overview:
      "A slow drive along Iceland's south coast — waterfalls, black sand beaches, and geothermal pools, with a night at the glacier lagoon.",
    highlights: ["Glacier lagoon at night", "Black sand beach walk", "Private geothermal pool session", "Small group of 8"],
    itinerary: [
      { day: 1, title: "Arrival Reykjavik", summary: "Rest and city walk." },
      { day: 2, title: "Golden Circle", summary: "Geysir, Gullfoss, Thingvellir." },
      { day: 3, title: "South coast", summary: "Seljalandsfoss, Skogafoss, Vik." },
      { day: 4, title: "Glacier lagoon", summary: "Jokulsarlon and diamond beach." },
      { day: 5, title: "Return to Reykjavik", summary: "Free afternoon and farewell dinner." },
      { day: 6, title: "Departure", summary: "Transfer to Keflavik Airport." },
    ],
    included: ["5 nights hotels", "All breakfasts, 3 dinners", "All transfers", "All entrance fees"],
    excluded: ["International flights"],
    hotel: "Boutique hotels along the route",
    meals: "Breakfast daily",
    transport: "Small-group minibus",
    pickup: "Keflavik Airport (KEF)",
    drop: "Keflavik Airport (KEF)",
    cancellationPolicy: "Free cancellation up to 45 days before departure.",
    refundPolicy: "Refunds within 10 business days.",
    faqs: [{ q: "Best month?", a: "September for northern lights, June for midnight sun." }],
    availableDates: [
      { id: "d1", startDate: iso(6, 8), endDate: iso(6, 13), totalSeats: 8, bookedSeats: 5 },
      { id: "d2", startDate: iso(9, 12), endDate: iso(9, 17), totalSeats: 8, bookedSeats: 2 },
    ],
    featured: false,
    isWomenSpecial: false,
  },
  {
    id: "p8",
    slug: "seniors-himalayan-heritage",
    title: "Himalayan Heritage",
    subtitle: "Eight comfortable days for 60+",
    destinationSlug: "himalayas",
    destinationName: "Indian Himalayas",
    categorySlug: "seniors",
    ageGroups: ["seniors"],
    travelType: "pilgrimage",
    difficulty: "easy",
    durationDays: 8,
    durationNights: 7,
    priceFrom: 2800,
    currency: "USD",
    rating: 4.9,
    reviewCount: 46,
    coverImage: IMG.himalayas,
    gallery: [IMG.himalayas, IMG.safetyPassport],
    overview:
      "A gentle, comfort-first tour of the lower Himalayas designed for travelers aged 60 and above. Every walk is optional; every day is unhurried.",
    highlights: ["Doctor on call throughout", "Low altitude, gentle pace", "Historic hill-station hotels", "Private car with wheelchair-friendly access"],
    itinerary: [
      { day: 1, title: "Arrival Chandigarh", summary: "Rest and welcome dinner." },
      { day: 2, title: "Drive to Shimla", summary: "Heritage hotel check-in." },
      { day: 3, title: "Shimla day", summary: "Toy train and Mall Road." },
      { day: 4, title: "Drive to Manali", summary: "Scenic route with breaks." },
      { day: 5, title: "Manali day", summary: "Hadimba temple and old town walk." },
      { day: 6, title: "Rest day", summary: "Free day at the resort." },
      { day: 7, title: "Return to Chandigarh", summary: "Farewell dinner." },
      { day: 8, title: "Departure", summary: "Transfer to Chandigarh Airport." },
    ],
    included: ["7 nights heritage hotels", "All meals", "All transfers", "Doctor on call"],
    excluded: ["Domestic flights"],
    hotel: "Heritage hotels throughout",
    meals: "All meals",
    transport: "Private car with wheelchair access",
    pickup: "Chandigarh Airport (IXC)",
    drop: "Chandigarh Airport (IXC)",
    cancellationPolicy: "Free cancellation up to 45 days before departure.",
    refundPolicy: "Refunds within 7 business days.",
    faqs: [{ q: "Medical support?", a: "A qualified doctor is on call for the group throughout the trip." }],
    availableDates: [
      { id: "d1", startDate: iso(4, 15), endDate: iso(4, 22), totalSeats: 12, bookedSeats: 8 },
      { id: "d2", startDate: iso(10, 10), endDate: iso(10, 17), totalSeats: 12, bookedSeats: 3 },
    ],
    featured: true,
    isWomenSpecial: false,
  },
  {
    id: "p9",
    slug: "bali-student-camp",
    title: "Bali Student Discovery",
    subtitle: "Ten days of learning for ages 12–17",
    destinationSlug: "bali",
    destinationName: "Bali, Indonesia",
    categorySlug: "students",
    ageGroups: ["students"],
    travelType: "cultural",
    difficulty: "easy",
    durationDays: 10,
    durationNights: 9,
    priceFrom: 2600,
    currency: "USD",
    rating: 4.8,
    reviewCount: 64,
    coverImage: IMG.bali,
    gallery: [IMG.bali],
    overview:
      "A structured discovery trip for students — culture, marine conservation, and creative workshops with accredited chaperones.",
    highlights: ["Accredited female + male chaperones", "Marine conservation project", "Cultural exchange with local school", "24/7 parent updates"],
    itinerary: [
      { day: 1, title: "Arrival", summary: "Group meet + orientation." },
      { day: 2, title: "Cultural day", summary: "Temple visits and traditional dance workshop." },
      { day: 3, title: "School exchange", summary: "Half day at a partner school." },
      { day: 4, title: "Conservation intro", summary: "Move to coast, marine biology basics." },
      { day: 5, title: "Reef work day 1", summary: "Snorkel survey with marine team." },
      { day: 6, title: "Reef work day 2", summary: "Coral fragment planting." },
      { day: 7, title: "Creative day", summary: "Photography and journaling workshop." },
      { day: 8, title: "Adventure day", summary: "Waterfall hike and river rafting." },
      { day: 9, title: "Reflection day", summary: "Group review and farewell dinner." },
      { day: 10, title: "Departure", summary: "Transfer to airport." },
    ],
    included: ["9 nights accommodation", "All meals", "All transfers", "All activities", "Chaperones"],
    excluded: ["International flights", "Passport & visa fees"],
    hotel: "Educational retreat centre + coastal camp",
    meals: "All meals",
    transport: "Private group bus",
    pickup: "Denpasar Airport (DPS)",
    drop: "Denpasar Airport (DPS)",
    cancellationPolicy: "Free cancellation up to 60 days before departure.",
    refundPolicy: "Refunds within 10 business days.",
    faqs: [{ q: "Chaperone-to-student ratio?", a: "1:6 minimum." }],
    availableDates: [
      { id: "d1", startDate: iso(6, 25), endDate: iso(7, 4), totalSeats: 24, bookedSeats: 18 },
      { id: "d2", startDate: iso(7, 25), endDate: iso(8, 3), totalSeats: 24, bookedSeats: 9 },
    ],
    featured: false,
    isWomenSpecial: false,
  },
  {
    id: "p10",
    slug: "weekend-in-naxos",
    title: "Weekend in Naxos",
    subtitle: "A three-day reset",
    destinationSlug: "naxos",
    destinationName: "Naxos, Greece",
    categorySlug: "weekend",
    ageGroups: ["young-adults", "professionals"],
    travelType: "leisure",
    difficulty: "easy",
    durationDays: 3,
    durationNights: 2,
    priceFrom: 950,
    currency: "USD",
    rating: 4.7,
    reviewCount: 33,
    coverImage: IMG.naxos,
    gallery: [IMG.naxos],
    overview:
      "A three-day weekend on Naxos designed for professionals — arrive Friday evening, leave Monday morning, actually rest in between.",
    highlights: ["Villa base, no moving around", "Slow food dinner", "One guided walk", "Nothing else on the schedule"],
    itinerary: [
      { day: 1, title: "Arrive Friday", summary: "Airport transfer, sunset dinner." },
      { day: 2, title: "One walk, one meal", summary: "Morning coastal walk, lunch, free afternoon, group dinner." },
      { day: 3, title: "Depart Monday morning", summary: "Airport transfer." },
    ],
    included: ["2 nights villa", "Breakfasts + one dinner", "All transfers"],
    excluded: ["Flights"],
    hotel: "Villa Aegea",
    meals: "Breakfast + one dinner",
    transport: "Private transfers",
    pickup: "Naxos Airport (JNX)",
    drop: "Naxos Airport (JNX)",
    cancellationPolicy: "Free cancellation up to 14 days before departure.",
    refundPolicy: "Refunds within 5 business days.",
    faqs: [{ q: "Best for?", a: "Professionals with limited time who want real rest." }],
    availableDates: [
      { id: "d1", startDate: iso(5, 15), endDate: iso(5, 17), totalSeats: 8, bookedSeats: 6 },
      { id: "d2", startDate: iso(9, 4), endDate: iso(9, 6), totalSeats: 8, bookedSeats: 3 },
    ],
    featured: false,
    isWomenSpecial: false,
  },
];
